version: '3'
services:
  web:
    image: "nginx:stable"
    ports:
     - "80:80"
    volumes:
     - ./nginx/html:/usr/share/nginx/html
     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  log_agent:
    build: log_agent/.
  log_server:
    build: log_server/.
    ports:
     - "514:514"
    volumes:
     - ./log_server/nginx:/var/log/nginx
